export const RSS_LIST_REQUEST = "RSS_LIST_REQUEST";
export const RSS_LIST_SUCCESS = "RSS_LIST_SUCCESS";
export const RSS_LIST_FAIL = "RSS_LIST_FAIL";

export const SINGLE_RSS_LIST_REQUEST = "SINGLE_RSS_LIST_REQUEST";
export const SINGLE_RSS_LIST_SUCCESS = "SINGLE_RSS_LIST_SUCCESS";
export const SINGLE_RSS_LIST_FAIL = "SINGLE_RSS_LIST_FAIL";
