name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Thehawk server
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: yarn i
    # - run: npm run build --if-present
    # - run: npm test